version: "3.4"

services:
  ui:
    build:
      context: ./ui
      # Use "./Dockerfile" instead for no SSL
      dockerfile: ./Dockerfile.ssl
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
    networks:
      - compsole-backend
    depends_on:
      - backend
    volumes:
      - /app/node_modules/
      - ./ui/docker_files/caddyfile:/etc/caddy/Caddyfile
      - ./.caddy/data:/data
      - ./.caddy/config:/config
    environment:
      - DOMAIN=compsole.example.com
  backend:
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: unless-stopped
    networks:
      - compsole-backend
    # ports:
    #   - 8080:8080
    depends_on:
      - db
    environment:
      # Server
      - GRAPHQL_HOSTNAME=localhost
      - CORS_ALLOWED_ORIGINS=http://localhost,http://localhost:3000
      - PORT=:8080
      # Disable this for no SSL
      - HTTPS_ENABLED=true
      - DEFAULT_ADMIN_USERNAME=compsole
      - DEFAULT_ADMIN_PASSWORD=compsole
      - GIN_MODE=release # set to 'debug' for development
      # Timeout in minutes
      - COOKIE_TIMEOUT=180
      # Window is in hours (time after invalid session to refresh REST tokens)
      - REFRESH_WINDOW=8
      # Change this to a randomly generated value (>= 64 bytes encouraged)
      - JWT_SECRET=secret
      # OAuth
      # - GITLAB_KEY=
      # - GITLAB_SECRET=
      # Database
      - PG_URI=postgresql://compsole:compsole@db/compsole
      # - PG_CONN_LIMIT=
      # - PG_IDLE_LIMIT=
      # Redis
      - REDIS_URI=redis:6379
      - REDIS_PASSWORD=
  db:
    image: library/postgres:14.4-alpine
    # ports:
    #   - 5432:5432
    restart: unless-stopped
    networks:
      - compsole-backend
    volumes:
      - compsole-db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=compsole
      - POSTGRES_PASSWORD=compsole
      - POSTGRES_DB=compsole
  redis:
    image: redis:5.0.7
    volumes:
      - redis-data:/data
    # ports:
    #   - "6379:6379"

volumes:
  compsole-db:
    driver: local
  redis-data:
    driver: local

networks:
  compsole-backend:
    driver: bridge
