version: "3.4"

services:
  db:
    image: library/postgres:14.4-alpine
    ports:
      - 5432:5432
    restart: unless-stopped
    volumes:
      - compsole-db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=compsole
      - POSTGRES_PASSWORD=compsole
      - POSTGRES_DB=compsole
  redis:
    image: redis:5.0.7
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"

volumes:
  compsole-db:
    driver: local
  redis-data:
    driver: local
