// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Action is the predicate function for action builders.
type Action func(*sql.Selector)

// Competition is the predicate function for competition builders.
type Competition func(*sql.Selector)

// Provider is the predicate function for provider builders.
type Provider func(*sql.Selector)

// ServiceAccount is the predicate function for serviceaccount builders.
type ServiceAccount func(*sql.Selector)

// Team is the predicate function for team builders.
type Team func(*sql.Selector)

// Token is the predicate function for token builders.
type Token func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)

// VmObject is the predicate function for vmobject builders.
type VmObject func(*sql.Selector)
