// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Team is the predicate function for team builders.
type Team func(*sql.Selector)

// VmObject is the predicate function for vmobject builders.
type VmObject func(*sql.Selector)
